name: Rust

on:
  push:
    branches: [ master, trunk ]
  pull_request:
    branches: [ master, trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
          version: latest
      - run: cargo deb --output="/tmp/imposter-pass-$GITHUB_SHA.deb"
      - name: Archive deb package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: /tmp/imposter-pass-$GITHUB_SHA.deb
